### ISSUE TITLE
Add bar chart type for better data visualization

### ISSUE THREAD

**Issue by schokotets** [FugiMuffi/exam-poll#9]
- exam marks are a linear quantity
- [pie charts make it hard to visually compare quantities](https://bernardmarr.com/why-you-shouldnt-use-pie-charts-in-your-dashboards-and-performance-reports/)
- a bar chart allows better visual correlation between mark and frequency
- therefore allows better distribution visualization

**Comment by FugiMuffi** [comment]
Thank you for the issue, those are some good points. A bar chart view has already been implemented by #7, so I will close this issue once this change is in main and published.
